### ISSUE TITLE
feature: support converting sdwebui Lora format to refiners

### ISSUE THREAD

**Issue by brycedrennan** [finegrain-ai/refiners#116]
I got pokemon Lora example working but it seems most loras are in the larger sdwebui format that modifies more than just the unet.

This one for example:
https://civitai.com/models/7109/modern-disney-lora

**Comment by deltheil** [comment]
> [...] it seems most loras are in the larger sdwebui format that modifies more than just the unet

This is a good point! FWIW, applying LoRA layers to the CLIP text encoder and/or the VAE is currently [supported](https://github.com/finegrain-ai/refiners/blob/92e8166c83669b5e17cf2ee2f66cb49e444f3025/src/refiners/foundationals/latent_diffusion/lora.py#L99). But that would require additional conversion scripts (e.g. even `scripts/conversion/convert_diffusers_lora.py` has limitations for now)

**Comment by catwell** [comment]
@brycedrennan As of now with the new SDLoraManager and the merge of https://github.com/finegrain-ai/refiners/pull/212 I think the Disney LoRA in your example works. It loads without warning and for instance using the prompt "a magical princess with golden hair, modern disney style" from the official repo, we get without the LoRA:

![out-std](https://github.com/finegrain-ai/refiners/assets/221332/2d55345e-9589-40d6-8e20-9581f07d8457)

and with the LoRA:

![out-disney](https://github.com/finegrain-ai/refiners/assets/221332/ffd3f40c-140a-4944-a270-d53bda6e23bd)

Do you know of other LoRAs that would not load? Otherwise we can possibly at last close that issue!

**Comment by brycedrennan** [comment]
That's great news! Lets close the issue and if any can't be loaded we can consider the causes separately.
